# Generated by Django 4.1.7 on 2023-02-22 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0002_employee_patient_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Appointment Date and time')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], max_length=10)),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason for visit')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Appointment notes')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='user_profile.employee')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='user_profile.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Body temperature')),
                ('pulse_rate', models.FloatField(verbose_name='Pulse rate')),
                ('respiration_rate', models.FloatField(verbose_name='Respiration rate')),
                ('blood_pressure', models.FloatField(verbose_name='Blood pressure')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visits.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.TimeField(verbose_name='Checkin time')),
                ('checkout_time', models.TimeField(verbose_name='Checkout Time')),
                ('symptoms', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Session notes')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visits.appointment')),
            ],
        ),
    ]
