# Generated by Django 4.1.7 on 2023-02-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='checkout_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Checkout Time'),
        ),
        migrations.AlterField(
            model_name='session',
            name='symptoms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
