# Generated by Django 4.1.7 on 2023-02-22 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('ID_Card', models.ImageField(blank=True, null=True, upload_to='profile/img/')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('dob', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date of Birth')),
                ('hire_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Hire Date')),
                ('job_type', models.CharField(choices=[('D', 'Doctor'), ('N', 'Nurse'), ('R', 'Receptionist'), ('HR', 'HR'), ('PR', 'Pharmacist')], max_length=2)),
                ('job_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Job Title')),
                ('department', models.TextField(blank=True, null=True, verbose_name='Medical History')),
                ('session_limit', models.IntegerField(blank=True, null=True, verbose_name='Daily Max hours')),
                ('manager', models.ManyToManyField(blank=True, related_name='emplyoee_manager', to='user_profile.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('ID_Card', models.ImageField(blank=True, null=True, upload_to='profile/img/')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('dob', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date of Birth')),
                ('blood_group', models.CharField(blank=True, choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3, verbose_name='Blood Group')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='Medical History')),
                ('curent_medications', models.TextField(blank=True, null=True, verbose_name='Current Medications')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
