# Generated by Django 4.1.7 on 2023-02-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_employee_patient_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Department'),
        ),
    ]
